import { inflateSync } from "node:zlib";
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

/**
 * Measure where each box icon's creature actually sits in its canvas.
 *
 * Every icon is a 68x56 sheet, but the figure inside is drawn at *true relative
 * scale* — Mr. Mime fills 37x31 of it, Wurmple 18x17. That is authentic, and at
 * full size it looks right. Shrunk into a 44px bench slot it means Wurmple gets
 * about twelve pixels of actual creature, which is not a Pokémon, it is a smudge.
 *
 * So we measure the alpha bounding box once, here, and the UI scales each icon
 * so its *figure* fills the slot rather than its canvas. Committed output, like
 * the dex — this reads 386 files and should never run in the app.
 *
 *   npx tsx scripts/icon-bounds.ts
 */

interface Bounds {
  x: number;
  y: number;
  w: number;
  h: number;
}

function decode(path: string): { width: number; height: number; rgba: Buffer } | null {
  const data = readFileSync(path);
  let pos = 8;
  let width = 0;
  let height = 0;
  let colourType = 0;
  const idat: Buffer[] = [];

  while (pos < data.length) {
    const length = data.readUInt32BE(pos);
    const type = data.toString("ascii", pos + 4, pos + 8);
    const body = data.subarray(pos + 8, pos + 8 + length);
    if (type === "IHDR") {
      width = body.readUInt32BE(0);
      height = body.readUInt32BE(4);
      colourType = body.readUInt8(9);
    } else if (type === "IDAT") {
      idat.push(body);
    }
    pos += 12 + length;
  }
  // Only true-colour-with-alpha appears in this set; anything else we skip
  // rather than guess at, so a bad measurement can never reach the UI.
  if (colourType !== 6) return null;

  const raw = inflateSync(Buffer.concat(idat));
  const stride = width * 4;
  const out = Buffer.alloc(height * stride);
  let prev = Buffer.alloc(stride);
  let i = 0;

  for (let y = 0; y < height; y++) {
    const filter = raw[i++];
    const line = Buffer.from(raw.subarray(i, i + stride));
    i += stride;
    for (let x = 0; x < stride; x++) {
      const a = x >= 4 ? line[x - 4]! : 0;
      const b = prev[x]!;
      const c = x >= 4 ? prev[x - 4]! : 0;
      const v = line[x]!;
      if (filter === 1) line[x] = (v + a) & 255;
      else if (filter === 2) line[x] = (v + b) & 255;
      else if (filter === 3) line[x] = (v + ((a + b) >> 1)) & 255;
      else if (filter === 4) {
        const p = a + b - c;
        const pa = Math.abs(p - a);
        const pb = Math.abs(p - b);
        const pc = Math.abs(p - c);
        const pr = pa <= pb && pa <= pc ? a : pb <= pc ? b : c;
        line[x] = (v + pr) & 255;
      }
    }
    line.copy(out, y * stride);
    prev = line;
  }
  return { width, height, rgba: out };
}

function bounds(path: string): Bounds | null {
  const img = decode(path);
  if (!img) return null;
  const { width, height, rgba } = img;

  let minX = width;
  let minY = height;
  let maxX = -1;
  let maxY = -1;

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      // A generous alpha floor: anti-aliased edges are part of the figure.
      if (rgba[(y * width + x) * 4 + 3]! <= 8) continue;
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
  }
  if (maxX < 0) return null;
  return { x: minX, y: minY, w: maxX - minX + 1, h: maxY - minY + 1 };
}

const dir = join(process.cwd(), "public", "icons");
const files = readdirSync(dir).filter((f) => f.endsWith(".png"));

const rows: string[] = [];
let canvasW = 68;
let canvasH = 56;

for (const file of files.sort((a, b) => Number(a.slice(0, -4)) - Number(b.slice(0, -4)))) {
  const id = Number(file.slice(0, -4));
  const b = bounds(join(dir, file));
  if (!b) continue;
  const img = decode(join(dir, file));
  if (img) {
    canvasW = img.width;
    canvasH = img.height;
  }
  rows.push(`  ${id}: [${b.x}, ${b.y}, ${b.w}, ${b.h}],`);
}

const out = `// Generated by scripts/icon-bounds.ts. Do not edit by hand.
//
// Where each box icon's creature actually sits inside its canvas, as
// [x, y, width, height]. The icons are drawn at true relative scale, which reads
// correctly at full size and turns small creatures into smudges at bench size —
// so the UI scales each one by its figure rather than its canvas.

export const ICON_CANVAS = { width: ${canvasW}, height: ${canvasH} } as const;

export const ICON_BOUNDS: Record<number, readonly [number, number, number, number]> = {
${rows.join("\n")}
};
`;

writeFileSync(join(process.cwd(), "src", "data", "iconBounds.ts"), out);
console.log(`Measured ${rows.length} icons.`);
