// Generated by scripts/fetch-encounters.ts. Do not edit by hand.
//
// What lives on each piece of Johto, taken from HeartGold's own encounter
// tables. Levels and frequencies are the games'; which roads join which towns
// is authored in places.ts and routes.ts, because that is map shape rather than
// wildlife.
//
// Rod encounters are excluded — they put level-40 Poliwag on a level-3 route.
// Species past #386 are excluded too; this game's dex stops there.

export interface Encounter {
  species: string;
  /** Relative frequency within this table. Need not be normalized. */
  weight: number;
  min: number;
  max: number;
}

export const ENCOUNTERS: Record<string, readonly Encounter[]> = {
  "route_29": [
    {
      "species": "hoothoot",
      "weight": 185,
      "min": 2,
      "max": 5
    },
    {
      "species": "pidgey",
      "weight": 110,
      "min": 2,
      "max": 4
    },
    {
      "species": "sentret",
      "weight": 80,
      "min": 2,
      "max": 3
    },
    {
      "species": "exeggcute",
      "weight": 40,
      "min": 2,
      "max": 5
    },
    {
      "species": "spinarak",
      "weight": 30,
      "min": 4,
      "max": 5
    },
    {
      "species": "pineco",
      "weight": 30,
      "min": 2,
      "max": 3
    },
    {
      "species": "plusle",
      "weight": 20,
      "min": 2,
      "max": 3
    },
    {
      "species": "minun",
      "weight": 20,
      "min": 3,
      "max": 3
    },
    {
      "species": "rattata",
      "weight": 15,
      "min": 2,
      "max": 4
    }
  ],
  "route_30": [
    {
      "species": "hoothoot",
      "weight": 130,
      "min": 2,
      "max": 5
    },
    {
      "species": "pidgey",
      "weight": 90,
      "min": 2,
      "max": 4
    },
    {
      "species": "caterpie",
      "weight": 85,
      "min": 3,
      "max": 4
    },
    {
      "species": "spinarak",
      "weight": 60,
      "min": 2,
      "max": 5
    },
    {
      "species": "rattata",
      "weight": 40,
      "min": 3,
      "max": 4
    },
    {
      "species": "exeggcute",
      "weight": 40,
      "min": 2,
      "max": 5
    },
    {
      "species": "pineco",
      "weight": 30,
      "min": 2,
      "max": 3
    },
    {
      "species": "metapod",
      "weight": 25,
      "min": 4,
      "max": 4
    },
    {
      "species": "linoone",
      "weight": 20,
      "min": 4,
      "max": 4
    },
    {
      "species": "whismur",
      "weight": 20,
      "min": 2,
      "max": 3
    }
  ],
  "route_31": [
    {
      "species": "hoothoot",
      "weight": 110,
      "min": 3,
      "max": 6
    },
    {
      "species": "caterpie",
      "weight": 70,
      "min": 4,
      "max": 5
    },
    {
      "species": "pidgey",
      "weight": 60,
      "min": 3,
      "max": 3
    },
    {
      "species": "spinarak",
      "weight": 60,
      "min": 3,
      "max": 6
    },
    {
      "species": "rattata",
      "weight": 40,
      "min": 4,
      "max": 5
    },
    {
      "species": "exeggcute",
      "weight": 40,
      "min": 3,
      "max": 6
    },
    {
      "species": "metapod",
      "weight": 30,
      "min": 5,
      "max": 5
    },
    {
      "species": "pineco",
      "weight": 30,
      "min": 3,
      "max": 4
    },
    {
      "species": "bellsprout",
      "weight": 20,
      "min": 3,
      "max": 3
    },
    {
      "species": "linoone",
      "weight": 20,
      "min": 3,
      "max": 3
    },
    {
      "species": "whismur",
      "weight": 20,
      "min": 3,
      "max": 4
    }
  ],
  "route_32": [
    {
      "species": "hoothoot",
      "weight": 130,
      "min": 4,
      "max": 7
    },
    {
      "species": "bellsprout",
      "weight": 80,
      "min": 6,
      "max": 6
    },
    {
      "species": "mareep",
      "weight": 50,
      "min": 6,
      "max": 6
    },
    {
      "species": "rattata",
      "weight": 45,
      "min": 4,
      "max": 6
    },
    {
      "species": "exeggcute",
      "weight": 40,
      "min": 4,
      "max": 7
    },
    {
      "species": "wooper",
      "weight": 35,
      "min": 6,
      "max": 6
    },
    {
      "species": "pineco",
      "weight": 30,
      "min": 4,
      "max": 5
    },
    {
      "species": "hoppip",
      "weight": 20,
      "min": 6,
      "max": 6
    },
    {
      "species": "linoone",
      "weight": 20,
      "min": 6,
      "max": 6
    },
    {
      "species": "whismur",
      "weight": 20,
      "min": 4,
      "max": 6
    },
    {
      "species": "zubat",
      "weight": 10,
      "min": 4,
      "max": 4
    }
  ],
  "route_33": [
    {
      "species": "spearow",
      "weight": 170,
      "min": 3,
      "max": 8
    },
    {
      "species": "hoppip",
      "weight": 70,
      "min": 6,
      "max": 8
    },
    {
      "species": "rattata",
      "weight": 65,
      "min": 4,
      "max": 7
    },
    {
      "species": "zubat",
      "weight": 45,
      "min": 4,
      "max": 8
    },
    {
      "species": "aipom",
      "weight": 40,
      "min": 3,
      "max": 8
    },
    {
      "species": "heracross",
      "weight": 30,
      "min": 3,
      "max": 5
    },
    {
      "species": "plusle",
      "weight": 20,
      "min": 6,
      "max": 7
    },
    {
      "species": "minun",
      "weight": 20,
      "min": 6,
      "max": 6
    }
  ],
  "route_34": [
    {
      "species": "hoothoot",
      "weight": 100,
      "min": 9,
      "max": 12
    },
    {
      "species": "drowzee",
      "weight": 50,
      "min": 10,
      "max": 12
    },
    {
      "species": "exeggcute",
      "weight": 40,
      "min": 9,
      "max": 12
    },
    {
      "species": "ralts",
      "weight": 40,
      "min": 10,
      "max": 11
    },
    {
      "species": "rattata",
      "weight": 35,
      "min": 11,
      "max": 13
    },
    {
      "species": "spinarak",
      "weight": 30,
      "min": 11,
      "max": 12
    },
    {
      "species": "pineco",
      "weight": 30,
      "min": 9,
      "max": 10
    },
    {
      "species": "linoone",
      "weight": 20,
      "min": 12,
      "max": 12
    },
    {
      "species": "whismur",
      "weight": 20,
      "min": 10,
      "max": 11
    },
    {
      "species": "abra",
      "weight": 10,
      "min": 10,
      "max": 10
    },
    {
      "species": "ditto",
      "weight": 5,
      "min": 10,
      "max": 10
    }
  ],
  "route_35": [
    {
      "species": "hoothoot",
      "weight": 105,
      "min": 10,
      "max": 14
    },
    {
      "species": "yanma",
      "weight": 41,
      "min": 12,
      "max": 12
    },
    {
      "species": "exeggcute",
      "weight": 40,
      "min": 10,
      "max": 14
    },
    {
      "species": "nidoran-f",
      "weight": 30,
      "min": 12,
      "max": 12
    },
    {
      "species": "nidoran-m",
      "weight": 30,
      "min": 12,
      "max": 12
    },
    {
      "species": "spinarak",
      "weight": 30,
      "min": 13,
      "max": 14
    },
    {
      "species": "pineco",
      "weight": 30,
      "min": 10,
      "max": 11
    },
    {
      "species": "drowzee",
      "weight": 20,
      "min": 14,
      "max": 14
    },
    {
      "species": "linoone",
      "weight": 20,
      "min": 14,
      "max": 14
    },
    {
      "species": "whismur",
      "weight": 20,
      "min": 12,
      "max": 12
    },
    {
      "species": "pidgey",
      "weight": 10,
      "min": 14,
      "max": 14
    },
    {
      "species": "abra",
      "weight": 10,
      "min": 10,
      "max": 10
    },
    {
      "species": "ditto",
      "weight": 4,
      "min": 10,
      "max": 10
    }
  ],
  "route_36": [
    {
      "species": "hoothoot",
      "weight": 125,
      "min": 4,
      "max": 15
    },
    {
      "species": "pidgey",
      "weight": 45,
      "min": 13,
      "max": 15
    },
    {
      "species": "exeggcute",
      "weight": 40,
      "min": 4,
      "max": 7
    },
    {
      "species": "nidoran-f",
      "weight": 30,
      "min": 12,
      "max": 12
    },
    {
      "species": "nidoran-m",
      "weight": 30,
      "min": 12,
      "max": 12
    },
    {
      "species": "spinarak",
      "weight": 30,
      "min": 6,
      "max": 7
    },
    {
      "species": "pineco",
      "weight": 30,
      "min": 4,
      "max": 5
    },
    {
      "species": "plusle",
      "weight": 20,
      "min": 12,
      "max": 12
    },
    {
      "species": "minun",
      "weight": 20,
      "min": 13,
      "max": 13
    },
    {
      "species": "growlithe",
      "weight": 15,
      "min": 13,
      "max": 15
    },
    {
      "species": "stantler",
      "weight": 5,
      "min": 13,
      "max": 13
    }
  ],
  "route_37": [
    {
      "species": "hoothoot",
      "weight": 120,
      "min": 12,
      "max": 17
    },
    {
      "species": "pidgey",
      "weight": 110,
      "min": 13,
      "max": 15
    },
    {
      "species": "spinarak",
      "weight": 70,
      "min": 13,
      "max": 17
    },
    {
      "species": "exeggcute",
      "weight": 40,
      "min": 12,
      "max": 17
    },
    {
      "species": "pineco",
      "weight": 30,
      "min": 12,
      "max": 14
    },
    {
      "species": "stantler",
      "weight": 30,
      "min": 15,
      "max": 15
    },
    {
      "species": "plusle",
      "weight": 20,
      "min": 13,
      "max": 15
    },
    {
      "species": "minun",
      "weight": 20,
      "min": 15,
      "max": 15
    },
    {
      "species": "growlithe",
      "weight": 15,
      "min": 14,
      "max": 15
    },
    {
      "species": "pidgeotto",
      "weight": 5,
      "min": 15,
      "max": 15
    }
  ],
  "route_38": [
    {
      "species": "hoothoot",
      "weight": 200,
      "min": 13,
      "max": 17
    },
    {
      "species": "exeggcute",
      "weight": 145,
      "min": 13,
      "max": 25
    },
    {
      "species": "rattata",
      "weight": 80,
      "min": 16,
      "max": 16
    },
    {
      "species": "raticate",
      "weight": 60,
      "min": 16,
      "max": 17
    },
    {
      "species": "spinarak",
      "weight": 60,
      "min": 15,
      "max": 17
    },
    {
      "species": "pineco",
      "weight": 60,
      "min": 13,
      "max": 15
    },
    {
      "species": "snubbull",
      "weight": 41,
      "min": 13,
      "max": 16
    },
    {
      "species": "magnemite",
      "weight": 40,
      "min": 16,
      "max": 16
    },
    {
      "species": "farfetchd",
      "weight": 40,
      "min": 16,
      "max": 16
    },
    {
      "species": "plusle",
      "weight": 40,
      "min": 16,
      "max": 17
    },
    {
      "species": "minun",
      "weight": 40,
      "min": 16,
      "max": 16
    },
    {
      "species": "miltank",
      "weight": 10,
      "min": 13,
      "max": 15
    },
    {
      "species": "tauros",
      "weight": 9,
      "min": 13,
      "max": 15
    }
  ],
  "route_40": [
    {
      "species": "krabby",
      "weight": 90,
      "min": 15,
      "max": 24
    },
    {
      "species": "shuckle",
      "weight": 10,
      "min": 23,
      "max": 28
    }
  ],
  "route_42": [
    {
      "species": "spearow",
      "weight": 190,
      "min": 13,
      "max": 16
    },
    {
      "species": "aipom",
      "weight": 40,
      "min": 13,
      "max": 16
    },
    {
      "species": "zubat",
      "weight": 30,
      "min": 14,
      "max": 16
    },
    {
      "species": "mankey",
      "weight": 30,
      "min": 15,
      "max": 15
    },
    {
      "species": "mareep",
      "weight": 30,
      "min": 13,
      "max": 13
    },
    {
      "species": "heracross",
      "weight": 30,
      "min": 13,
      "max": 14
    },
    {
      "species": "linoone",
      "weight": 20,
      "min": 14,
      "max": 14
    },
    {
      "species": "whismur",
      "weight": 20,
      "min": 13,
      "max": 15
    },
    {
      "species": "flaaffy",
      "weight": 10,
      "min": 15,
      "max": 17
    }
  ],
  "route_43": [
    {
      "species": "hoothoot",
      "weight": 115,
      "min": 15,
      "max": 18
    },
    {
      "species": "pidgeotto",
      "weight": 45,
      "min": 17,
      "max": 17
    },
    {
      "species": "exeggcute",
      "weight": 40,
      "min": 15,
      "max": 18
    },
    {
      "species": "flaaffy",
      "weight": 40,
      "min": 15,
      "max": 17
    },
    {
      "species": "venonat",
      "weight": 35,
      "min": 15,
      "max": 18
    },
    {
      "species": "girafarig",
      "weight": 30,
      "min": 15,
      "max": 15
    },
    {
      "species": "pineco",
      "weight": 30,
      "min": 15,
      "max": 16
    },
    {
      "species": "mareep",
      "weight": 25,
      "min": 15,
      "max": 16
    },
    {
      "species": "noctowl",
      "weight": 20,
      "min": 17,
      "max": 17
    },
    {
      "species": "linoone",
      "weight": 20,
      "min": 17,
      "max": 17
    },
    {
      "species": "whismur",
      "weight": 20,
      "min": 15,
      "max": 15
    }
  ],
  "route_44": [
    {
      "species": "spearow",
      "weight": 130,
      "min": 21,
      "max": 24
    },
    {
      "species": "aipom",
      "weight": 40,
      "min": 21,
      "max": 24
    },
    {
      "species": "weepinbell",
      "weight": 35,
      "min": 22,
      "max": 24
    },
    {
      "species": "tangela",
      "weight": 30,
      "min": 23,
      "max": 23
    },
    {
      "species": "heracross",
      "weight": 30,
      "min": 21,
      "max": 22
    },
    {
      "species": "bellsprout",
      "weight": 20,
      "min": 22,
      "max": 22
    },
    {
      "species": "linoone",
      "weight": 20,
      "min": 22,
      "max": 22
    },
    {
      "species": "whismur",
      "weight": 20,
      "min": 22,
      "max": 23
    },
    {
      "species": "lickitung",
      "weight": 15,
      "min": 24,
      "max": 26
    }
  ],
  "route_45": [
    {
      "species": "spearow",
      "weight": 130,
      "min": 23,
      "max": 27
    },
    {
      "species": "graveler",
      "weight": 40,
      "min": 23,
      "max": 27
    },
    {
      "species": "aipom",
      "weight": 40,
      "min": 23,
      "max": 27
    },
    {
      "species": "swablu",
      "weight": 40,
      "min": 23,
      "max": 23
    },
    {
      "species": "geodude",
      "weight": 30,
      "min": 23,
      "max": 23
    },
    {
      "species": "heracross",
      "weight": 30,
      "min": 23,
      "max": 25
    },
    {
      "species": "gligar",
      "weight": 20,
      "min": 24,
      "max": 24
    },
    {
      "species": "linoone",
      "weight": 20,
      "min": 24,
      "max": 24
    },
    {
      "species": "whismur",
      "weight": 20,
      "min": 23,
      "max": 23
    },
    {
      "species": "phanpy",
      "weight": 10,
      "min": 20,
      "max": 20
    }
  ],
  "route_46": [
    {
      "species": "spearow",
      "weight": 200,
      "min": 2,
      "max": 5
    },
    {
      "species": "rattata",
      "weight": 55,
      "min": 2,
      "max": 4
    },
    {
      "species": "geodude",
      "weight": 45,
      "min": 2,
      "max": 3
    },
    {
      "species": "aipom",
      "weight": 40,
      "min": 2,
      "max": 5
    },
    {
      "species": "heracross",
      "weight": 30,
      "min": 2,
      "max": 3
    },
    {
      "species": "plusle",
      "weight": 20,
      "min": 2,
      "max": 3
    },
    {
      "species": "minun",
      "weight": 20,
      "min": 2,
      "max": 2
    }
  ],
  "ruins_of_alph": [
    {
      "species": "geodude",
      "weight": 100,
      "min": 3,
      "max": 14
    },
    {
      "species": "natu",
      "weight": 90,
      "min": 18,
      "max": 24
    },
    {
      "species": "linoone",
      "weight": 20,
      "min": 18,
      "max": 18
    },
    {
      "species": "whismur",
      "weight": 20,
      "min": 20,
      "max": 22
    },
    {
      "species": "smeargle",
      "weight": 10,
      "min": 20,
      "max": 22
    }
  ],
  "union_cave": [
    {
      "species": "zubat",
      "weight": 80,
      "min": 5,
      "max": 22
    },
    {
      "species": "geodude",
      "weight": 70,
      "min": 6,
      "max": 21
    },
    {
      "species": "sandshrew",
      "weight": 60,
      "min": 6,
      "max": 8
    },
    {
      "species": "makuhita",
      "weight": 60,
      "min": 5,
      "max": 22
    },
    {
      "species": "absol",
      "weight": 60,
      "min": 6,
      "max": 22
    },
    {
      "species": "raticate",
      "weight": 30,
      "min": 22,
      "max": 22
    },
    {
      "species": "rattata",
      "weight": 20,
      "min": 4,
      "max": 20
    },
    {
      "species": "onix",
      "weight": 20,
      "min": 6,
      "max": 23
    },
    {
      "species": "golbat",
      "weight": 20,
      "min": 22,
      "max": 22
    }
  ],
  "slowpoke_well": [
    {
      "species": "zubat",
      "weight": 165,
      "min": 5,
      "max": 23
    },
    {
      "species": "makuhita",
      "weight": 40,
      "min": 7,
      "max": 19
    },
    {
      "species": "absol",
      "weight": 40,
      "min": 5,
      "max": 23
    },
    {
      "species": "slowpoke",
      "weight": 30,
      "min": 6,
      "max": 23
    },
    {
      "species": "golbat",
      "weight": 5,
      "min": 23,
      "max": 23
    }
  ],
  "ilex_forest": [
    {
      "species": "caterpie",
      "weight": 140,
      "min": 3,
      "max": 6
    },
    {
      "species": "hoothoot",
      "weight": 110,
      "min": 3,
      "max": 8
    },
    {
      "species": "metapod",
      "weight": 70,
      "min": 3,
      "max": 6
    },
    {
      "species": "oddish",
      "weight": 60,
      "min": 5,
      "max": 6
    },
    {
      "species": "pineco",
      "weight": 30,
      "min": 6,
      "max": 8
    },
    {
      "species": "zubat",
      "weight": 25,
      "min": 5,
      "max": 6
    },
    {
      "species": "paras",
      "weight": 25,
      "min": 5,
      "max": 6
    },
    {
      "species": "numel",
      "weight": 20,
      "min": 6,
      "max": 6
    },
    {
      "species": "spoink",
      "weight": 20,
      "min": 5,
      "max": 6
    },
    {
      "species": "butterfree",
      "weight": 10,
      "min": 6,
      "max": 8
    },
    {
      "species": "noctowl",
      "weight": 10,
      "min": 6,
      "max": 8
    }
  ],
  "national_park": [
    {
      "species": "hoothoot",
      "weight": 200,
      "min": 10,
      "max": 15
    },
    {
      "species": "caterpie",
      "weight": 120,
      "min": 7,
      "max": 36
    },
    {
      "species": "exeggcute",
      "weight": 105,
      "min": 10,
      "max": 20
    },
    {
      "species": "metapod",
      "weight": 80,
      "min": 9,
      "max": 36
    },
    {
      "species": "weedle",
      "weight": 40,
      "min": 7,
      "max": 36
    },
    {
      "species": "wurmple",
      "weight": 40,
      "min": 24,
      "max": 36
    },
    {
      "species": "nincada",
      "weight": 40,
      "min": 26,
      "max": 36
    },
    {
      "species": "pidgey",
      "weight": 35,
      "min": 10,
      "max": 14
    },
    {
      "species": "spinarak",
      "weight": 30,
      "min": 13,
      "max": 15
    },
    {
      "species": "pineco",
      "weight": 30,
      "min": 10,
      "max": 12
    },
    {
      "species": "sunkern",
      "weight": 25,
      "min": 10,
      "max": 12
    },
    {
      "species": "kakuna",
      "weight": 20,
      "min": 9,
      "max": 36
    },
    {
      "species": "paras",
      "weight": 20,
      "min": 10,
      "max": 34
    },
    {
      "species": "venonat",
      "weight": 20,
      "min": 10,
      "max": 32
    },
    {
      "species": "scyther",
      "weight": 20,
      "min": 13,
      "max": 28
    },
    {
      "species": "pinsir",
      "weight": 20,
      "min": 13,
      "max": 28
    },
    {
      "species": "plusle",
      "weight": 20,
      "min": 10,
      "max": 10
    },
    {
      "species": "minun",
      "weight": 20,
      "min": 12,
      "max": 12
    },
    {
      "species": "butterfree",
      "weight": 10,
      "min": 12,
      "max": 30
    },
    {
      "species": "beedrill",
      "weight": 10,
      "min": 12,
      "max": 30
    },
    {
      "species": "silcoon",
      "weight": 10,
      "min": 24,
      "max": 36
    },
    {
      "species": "cascoon",
      "weight": 10,
      "min": 24,
      "max": 36
    },
    {
      "species": "volbeat",
      "weight": 10,
      "min": 26,
      "max": 36
    },
    {
      "species": "illumise",
      "weight": 10,
      "min": 26,
      "max": 36
    },
    {
      "species": "beautifly",
      "weight": 5,
      "min": 25,
      "max": 32
    },
    {
      "species": "dustox",
      "weight": 5,
      "min": 25,
      "max": 32
    }
  ],
  "burned_tower": [
    {
      "species": "rattata",
      "weight": 105,
      "min": 13,
      "max": 16
    },
    {
      "species": "koffing",
      "weight": 85,
      "min": 14,
      "max": 16
    },
    {
      "species": "zigzagoon",
      "weight": 40,
      "min": 13,
      "max": 14
    },
    {
      "species": "meditite",
      "weight": 40,
      "min": 15,
      "max": 16
    },
    {
      "species": "spinda",
      "weight": 40,
      "min": 15,
      "max": 16
    },
    {
      "species": "magmar",
      "weight": 20,
      "min": 14,
      "max": 16
    },
    {
      "species": "zubat",
      "weight": 15,
      "min": 14,
      "max": 15
    },
    {
      "species": "raticate",
      "weight": 5,
      "min": 15,
      "max": 15
    }
  ],
  "mt_mortar": [
    {
      "species": "geodude",
      "weight": 75,
      "min": 13,
      "max": 31
    },
    {
      "species": "zubat",
      "weight": 65,
      "min": 13,
      "max": 15
    },
    {
      "species": "machop",
      "weight": 60,
      "min": 13,
      "max": 28
    },
    {
      "species": "makuhita",
      "weight": 60,
      "min": 14,
      "max": 31
    },
    {
      "species": "absol",
      "weight": 60,
      "min": 13,
      "max": 32
    },
    {
      "species": "marill",
      "weight": 41,
      "min": 13,
      "max": 15
    },
    {
      "species": "machoke",
      "weight": 30,
      "min": 32,
      "max": 32
    },
    {
      "species": "graveler",
      "weight": 30,
      "min": 31,
      "max": 31
    },
    {
      "species": "rattata",
      "weight": 24,
      "min": 14,
      "max": 16
    },
    {
      "species": "raticate",
      "weight": 10,
      "min": 30,
      "max": 30
    },
    {
      "species": "golbat",
      "weight": 5,
      "min": 30,
      "max": 30
    }
  ],
  "lake_of_rage": [
    {
      "species": "hoothoot",
      "weight": 115,
      "min": 14,
      "max": 19
    },
    {
      "species": "exeggcute",
      "weight": 40,
      "min": 14,
      "max": 19
    },
    {
      "species": "pineco",
      "weight": 30,
      "min": 14,
      "max": 16
    },
    {
      "species": "venonat",
      "weight": 15,
      "min": 17,
      "max": 19
    }
  ],
  "ice_path": [
    {
      "species": "swinub",
      "weight": 120,
      "min": 21,
      "max": 24
    },
    {
      "species": "zubat",
      "weight": 90,
      "min": 22,
      "max": 23
    },
    {
      "species": "golbat",
      "weight": 90,
      "min": 22,
      "max": 23
    },
    {
      "species": "makuhita",
      "weight": 60,
      "min": 22,
      "max": 23
    },
    {
      "species": "absol",
      "weight": 60,
      "min": 21,
      "max": 23
    },
    {
      "species": "jynx",
      "weight": 30,
      "min": 22,
      "max": 23
    }
  ],
  "dragons_den": [
    {
      "species": "magikarp",
      "weight": 90,
      "min": 5,
      "max": 20
    },
    {
      "species": "dratini",
      "weight": 10,
      "min": 5,
      "max": 15
    }
  ],
  "dark_cave": [
    {
      "species": "dunsparce",
      "weight": 131,
      "min": 2,
      "max": 8
    },
    {
      "species": "geodude",
      "weight": 100,
      "min": 2,
      "max": 23
    },
    {
      "species": "zubat",
      "weight": 69,
      "min": 2,
      "max": 23
    },
    {
      "species": "makuhita",
      "weight": 40,
      "min": 2,
      "max": 25
    },
    {
      "species": "absol",
      "weight": 40,
      "min": 2,
      "max": 23
    },
    {
      "species": "graveler",
      "weight": 20,
      "min": 25,
      "max": 25
    },
    {
      "species": "wobbuffet",
      "weight": 15,
      "min": 20,
      "max": 25
    },
    {
      "species": "golbat",
      "weight": 5,
      "min": 23,
      "max": 23
    }
  ],
  "sprout_tower": [
    {
      "species": "rattata",
      "weight": 370,
      "min": 3,
      "max": 6
    },
    {
      "species": "gastly",
      "weight": 170,
      "min": 3,
      "max": 6
    },
    {
      "species": "zigzagoon",
      "weight": 40,
      "min": 3,
      "max": 4
    },
    {
      "species": "meditite",
      "weight": 40,
      "min": 5,
      "max": 5
    },
    {
      "species": "spinda",
      "weight": 40,
      "min": 5,
      "max": 5
    }
  ]
};
