// Generated by scripts/fetch-trainers.ts. Do not edit by hand.
//
// Who can look like what. Two rules, both of them the player's:
//
//   - a portrait respects the trainer's type — no Fire specialist in a Bug
//     Catcher's hat;
//   - rank matters — youngsters and schoolkids never hold a league post, so
//     Leaders, Elite seats and Champions draw only from `senior`.

export interface LookPool {
  /** League-worthy: canon Leaders of the type, and veterans where thin. */
  readonly senior: readonly string[];
  /** Route classes — Gym Trainers, Rangers, Handlers. */
  readonly junior: readonly string[];
}

/** The Champion looks the part whatever they specialise in. */
export const CHAMPION_LOOKS: readonly string[] = ["cynthia", "steven", "lance", "wallace"];

export const TRAINER_LOOKS: Record<string, LookPool> = {
  normal: {
    senior: ["whitney", "norman", "veteran", "veteranf"],
    junior: ["youngster", "lass", "schoolkid", "camper", "picnicker", "pokefan", "pokefanf", "teacher"],
  },
  fire: {
    senior: ["blaine", "flannery"],
    junior: ["firebreather", "biker", "roughneck", "camper"],
  },
  water: {
    senior: ["misty", "wallace", "juan", "crasherwake"],
    junior: ["swimmer", "swimmerf", "fisherman", "sailor", "tuber", "tuberf"],
  },
  electric: {
    senior: ["ltsurge", "wattson", "volkner"],
    junior: ["guitarist", "scientist", "scientistf", "officeworker", "worker"],
  },
  grass: {
    senior: ["erika", "gardenia"],
    junior: ["aromalady", "gardener", "picnicker", "rancher", "camper"],
  },
  ice: {
    senior: ["pryce", "candice", "glacia"],
    junior: ["skier", "skierf", "workerice"],
  },
  fighting: {
    senior: ["brawly", "chuck", "maylene", "bruno"],
    junior: ["blackbelt", "battlegirl", "striker", "smasher", "linebacker"],
  },
  poison: {
    senior: ["koga", "veteran"],
    junior: ["burglar", "punkguy", "punkgirl", "biker"],
  },
  ground: {
    senior: ["giovanni", "bertha"],
    junior: ["hiker", "ruinmaniac", "worker", "rancher"],
  },
  flying: {
    senior: ["falkner", "winona", "skyla"],
    junior: ["birdkeeper", "pilot", "cyclist", "cyclistf"],
  },
  psychic: {
    senior: ["sabrina", "tate", "liza", "will", "lucian"],
    junior: ["psychic", "psychicf", "medium", "supernerd"],
  },
  bug: {
    senior: ["bugsy", "aaron"],
    junior: ["bugcatcher", "ninjaboy", "picnicker"],
  },
  rock: {
    senior: ["brock", "roxanne", "roark"],
    junior: ["hiker", "ruinmaniac", "collector", "worker"],
  },
  ghost: {
    senior: ["morty", "fantina"],
    junior: ["medium", "madame", "artist", "psychicf"],
  },
  dragon: {
    senior: ["clair", "lance"],
    junior: ["dragontamer", "acetrainer", "acetrainerf"],
  },
  dark: {
    senior: ["karen", "sidney"],
    junior: ["punkguy", "punkgirl", "biker", "roughneck", "burglar"],
  },
  steel: {
    senior: ["jasmine", "byron", "steven"],
    junior: ["worker", "scientist", "officeworker", "policeman"],
  },
  fairy: {
    senior: ["valerie", "veteranf", "lady"],
    junior: ["parasollady", "beauty", "madame", "twins"],
  },
};
